create table if not exists public.karyawan (
  id bigint generated by default as identity primary key,
  nama text not null,
  username text not null unique,
  brand text not null,
  kata_sandi text not null,
  foto text,
  role text not null default 'karyawan' check (role in ('karyawan', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public."order" (
  id bigint generated by default as identity primary key,
  user_id bigint references public.karyawan(id) on delete set null,
  nama text not null,
  username text not null,
  -- Diisi dari input Brand pada halaman order.html.
  brand text not null,
  -- Diisi dari input Kategori pada halaman order.html.
  kategori text not null default 'Order POP',
  ukuran_kertas text not null,
  lembar integer not null check (lembar > 0),
  promo text not null,
  status text not null default 'belum diproses' check (status in ('belum diproses', 'sedang diproses', 'selesai', 'ditolak')),
  admin_id bigint references public.karyawan(id) on delete set null,
  admin_nama text,
  alasan_tolak text,
  created_at timestamptz not null default now()
);

create table if not exists public.notifikasi (
  id bigint generated by default as identity primary key,
  target_role text check (target_role in ('admin')),
  target_user_id bigint references public.karyawan(id) on delete cascade,
  order_id bigint references public."order"(id) on delete cascade,
  judul text not null,
  pesan text not null,
  dibaca boolean not null default false,
  created_at timestamptz not null default now(),
  check (target_role is not null or target_user_id is not null)
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.karyawan(id) on delete cascade,
  target_role text check (target_role in ('admin')),
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (target_role is not null or user_id is not null)
);

create index if not exists order_username_idx on public."order" (username);
create index if not exists order_created_at_idx on public."order" (created_at);
create index if not exists order_status_idx on public."order" (status);
create index if not exists notifikasi_target_role_idx on public.notifikasi (target_role);
create index if not exists notifikasi_target_user_id_idx on public.notifikasi (target_user_id);
create index if not exists notifikasi_created_at_idx on public.notifikasi (created_at);
create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions (user_id);
create index if not exists push_subscriptions_target_role_idx on public.push_subscriptions (target_role);

alter table public.karyawan enable row level security;
alter table public."order" enable row level security;
alter table public.notifikasi enable row level security;
alter table public.push_subscriptions enable row level security;

create policy "Anon can read karyawan"
on public.karyawan for select
to anon
using (true);

create policy "Anon can insert karyawan"
on public.karyawan for insert
to anon
with check (true);

create policy "Anon can update karyawan"
on public.karyawan for update
to anon
using (true)
with check (true);

create policy "Anon can read orders"
on public."order" for select
to anon
using (true);

create policy "Anon can insert orders"
on public."order" for insert
to anon
with check (true);

create policy "Anon can update orders"
on public."order" for update
to anon
using (true)
with check (true);

create policy "Anon can delete expired orders"
on public."order" for delete
to anon
using (created_at < now() - interval '31 days');

create policy "Anon can read notifications"
on public.notifikasi for select
to anon
using (true);

create policy "Anon can insert notifications"
on public.notifikasi for insert
to anon
with check (true);

create policy "Anon can update notifications"
on public.notifikasi for update
to anon
using (true)
with check (true);

create policy "Anon can read push subscriptions"
on public.push_subscriptions for select
to anon
using (true);

create policy "Anon can insert push subscriptions"
on public.push_subscriptions for insert
to anon
with check (true);

create policy "Anon can update push subscriptions"
on public.push_subscriptions for update
to anon
using (true)
with check (true);

do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'notifikasi'
  ) then
    alter publication supabase_realtime add table public.notifikasi;
  end if;
end $$;

-- Jalankan ini untuk membuat akun admin awal, lalu ubah nilainya sesuai kebutuhan.
insert into public.karyawan (nama, username, brand, kata_sandi, role)
values ('Admin VM', 'admin', 'VM', 'admin123', 'admin')
on conflict (username) do nothing;
