create table if not exists public.notifikasi (
  id bigint generated by default as identity primary key,
  target_role text check (target_role in ('admin')),
  target_user_id bigint references public.karyawan(id) on delete cascade,
  order_id bigint references public."order"(id) on delete cascade,
  judul text not null,
  pesan text not null,
  dibaca boolean not null default false,
  created_at timestamptz not null default now(),
  check (target_role is not null or target_user_id is not null)
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.karyawan(id) on delete cascade,
  target_role text check (target_role in ('admin')),
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (target_role is not null or user_id is not null)
);

create index if not exists notifikasi_target_role_idx on public.notifikasi (target_role);
create index if not exists notifikasi_target_user_id_idx on public.notifikasi (target_user_id);
create index if not exists notifikasi_created_at_idx on public.notifikasi (created_at);
create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions (user_id);
create index if not exists push_subscriptions_target_role_idx on public.push_subscriptions (target_role);

alter table public.notifikasi enable row level security;
alter table public.push_subscriptions enable row level security;

drop policy if exists "Anon can read notifications" on public.notifikasi;
create policy "Anon can read notifications"
on public.notifikasi for select
to anon
using (true);

drop policy if exists "Anon can insert notifications" on public.notifikasi;
create policy "Anon can insert notifications"
on public.notifikasi for insert
to anon
with check (true);

drop policy if exists "Anon can update notifications" on public.notifikasi;
create policy "Anon can update notifications"
on public.notifikasi for update
to anon
using (true)
with check (true);

drop policy if exists "Anon can read push subscriptions" on public.push_subscriptions;
create policy "Anon can read push subscriptions"
on public.push_subscriptions for select
to anon
using (true);

drop policy if exists "Anon can insert push subscriptions" on public.push_subscriptions;
create policy "Anon can insert push subscriptions"
on public.push_subscriptions for insert
to anon
with check (true);

drop policy if exists "Anon can update push subscriptions" on public.push_subscriptions;
create policy "Anon can update push subscriptions"
on public.push_subscriptions for update
to anon
using (true)
with check (true);

do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'notifikasi'
  ) then
    alter publication supabase_realtime add table public.notifikasi;
  end if;
end $$;
